[package]
name = "cli_games"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "6.0.0"
inquire = "0.7.5"
rand = "0.9.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
rusqlite = { version = "0.33.0", features = ["bundled"] }
